import {
  LanguageFunctionInfo,
  ExamQuestion,
  TextStudyUnit,
  ScrambleExerciseItem,
} from './types';

export const LANGUAGE_FUNCTIONS: LanguageFunctionInfo[] = [
  {
    id: 'referencial',
    nameEs: 'Referencial / representativa',
    nameArm: 'Տեղեկատվական / ներկայացուցչական',
    aliasesEs: 'Informativa, representativa',
    purposeEs: 'Informar sobre hechos o realidad',
    purposeArm: 'տեղեկություն հաղորդել',
    shortcutEs: 'Informar → referencial',
    shortcutArm: 'Տեղեկացնել → տեղեկատվական',
    formulaEs: 'Es referencial porque transmite información objetiva.',
    formulaArm: 'Տեղեկատվական է, որովհետև օբյեկտիվ տեղեկություն է հաղորդում։',
    color: 'emerald',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-900/40',
    badgeText: 'text-emerald-800 dark:text-emerald-200',
    borderColor: 'border-emerald-300 dark:border-emerald-700',
    iconName: 'Info',
    elementOfCommunication: {
      es: 'Contexto / Realidad (referente)',
      arm: 'Իրադրություն / Իրականություն (կոնտեքստ)',
    },
  },
  {
    id: 'expresiva',
    nameEs: 'Expresiva / emotiva',
    nameArm: 'Զգացմունքային / արտահայտչական',
    aliasesEs: 'Emotiva, sintomática',
    purposeEs: 'Expresar sentimientos u opiniones',
    purposeArm: 'արտահայտել զգացմունքներ կամ կարծիք',
    shortcutEs: 'Sentir → expresiva',
    shortcutArm: 'Զգալ → զգացմունքային',
    formulaEs: 'Es expresiva porque muestra los sentimientos del emisor.',
    formulaArm: 'Զգացմունքային է, որովհետև ցույց է տալիս խոսողի զգացմունքները։',
    color: 'amber',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40',
    badgeText: 'text-amber-800 dark:text-amber-200',
    borderColor: 'border-amber-300 dark:border-amber-700',
    iconName: 'HeartHandshake',
    elementOfCommunication: {
      es: 'Emisor (quien habla)',
      arm: 'Խոսող / Հաղորդող (emisor)',
    },
  },
  {
    id: 'apelativa',
    nameEs: 'Apelativa / conativa',
    nameArm: 'Դիմողական / կոնատիվ',
    aliasesEs: 'Conativa, directiva',
    purposeEs: 'Conseguir que el receptor haga algo',
    purposeArm: 'ազդել լսողի վրա, խնդրել կամ հրամայել',
    shortcutEs: 'Ordenar/pedir → apelativa',
    shortcutArm: 'Հրամայել/խնդրել → դիմողական',
    formulaEs: 'Es apelativa porque intenta influir en el receptor.',
    formulaArm: 'Դիմողական է, որովհետև փորձում է ազդել լսողի վրա։',
    color: 'blue',
    badgeBg: 'bg-blue-100 dark:bg-blue-900/40',
    badgeText: 'text-blue-800 dark:text-blue-200',
    borderColor: 'border-blue-300 dark:border-blue-700',
    iconName: 'Megaphone',
    elementOfCommunication: {
      es: 'Receptor (a quien se dirige)',
      arm: 'Լսող / Ընդունող (receptor)',
    },
  },
  {
    id: 'fatica',
    nameEs: 'Fática / de contacto',
    nameArm: 'Ֆատիկ / հաղորդակցական կապի',
    aliasesEs: 'De contacto',
    purposeEs: 'Iniciar, mantener o comprobar la comunicación',
    purposeArm: 'սկսել, շարունակել կամ ստուգել հաղորդակցությունը',
    shortcutEs: 'Comprobar contacto → fática',
    shortcutArm: 'Ստուգել կապը → ֆատիկ',
    formulaEs: 'Es fática porque comprueba o mantiene la comunicación.',
    formulaArm: 'Ֆատիկ է, որովհետև ստուգում կամ պահպանում է հաղորդակցությունը։',
    color: 'purple',
    badgeBg: 'bg-purple-100 dark:bg-purple-900/40',
    badgeText: 'text-purple-800 dark:text-purple-200',
    borderColor: 'border-purple-300 dark:border-purple-700',
    iconName: 'PhoneCall',
    elementOfCommunication: {
      es: 'Canal (el medio de transmisión)',
      arm: 'Կապուղի (canal)',
    },
  },
  {
    id: 'metalinguistica',
    nameEs: 'Metalingüística',
    nameArm: 'Մետալեզվական',
    aliasesEs: 'Sobre la propia lengua',
    purposeEs: 'Hablar sobre la propia lengua',
    purposeArm: 'խոսել հենց լեզվի մասին',
    shortcutEs: 'Hablar de palabras → metalingüística',
    shortcutArm: 'Խոսել բառերի մասին → մետալեզվական',
    formulaEs: 'Es metalingüística porque habla sobre la lengua.',
    formulaArm: 'Մետալեզվական է, որովհետև խոսում է լեզվի մասին։',
    color: 'rose',
    badgeBg: 'bg-rose-100 dark:bg-rose-900/40',
    badgeText: 'text-rose-800 dark:text-rose-200',
    borderColor: 'border-rose-300 dark:border-rose-700',
    iconName: 'BookOpen',
    elementOfCommunication: {
      es: 'Código (el idioma o reglas)',
      arm: 'Կոդ / Լեզվական համակարգ (código)',
    },
  },
  {
    id: 'poetica',
    nameEs: 'Poética / estética',
    nameArm: 'Բանաստեղծական / գեղագիտական',
    aliasesEs: 'Estética',
    purposeEs: 'Llamar la atención sobre la forma del mensaje',
    purposeArm: 'ուշադրություն դարձնել խոսքի գեղեցիկ/ստեղծագործ ձևին',
    shortcutEs: 'Mensaje bonito/creativo → poética',
    shortcutArm: 'Գեղեցիկ/ստեղծագործ հաղորդագրություն → բանաստեղծական',
    formulaEs: 'Es poética porque destaca la forma estética del mensaje.',
    formulaArm: 'Բանաստեղծական է, որովհետև կարևորում է հաղորդագրության գեղեցիկ ձևը։',
    color: 'indigo',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-900/40',
    badgeText: 'text-indigo-800 dark:text-indigo-200',
    borderColor: 'border-indigo-300 dark:border-indigo-700',
    iconName: 'Sparkles',
    elementOfCommunication: {
      es: 'Mensaje (la forma del texto)',
      arm: 'Հաղորդագրություն / Խոսքի ձև (mensaje)',
    },
  },
];

export const EXAM_FORMULAS = [
  {
    functionId: 'referencial',
    title: 'Referencial',
    formulaEs: 'Es referencial porque transmite información objetiva.',
    formulaArm: 'Տեղեկատվական է, որովհետև օբյեկտիվ տեղեկություն է հաղորդում։',
  },
  {
    functionId: 'expresiva',
    title: 'Expresiva',
    formulaEs: 'Es expresiva porque muestra los sentimientos del emisor.',
    formulaArm: 'Զգացմունքային է, որովհետև ցույց է տալիս խոսողի զգացմունքները։',
  },
  {
    functionId: 'apelativa',
    title: 'Apelativa',
    formulaEs: 'Es apelativa porque intenta influir en el receptor.',
    formulaArm: 'Դիմողական է, որովհետև փորձում է ազդել լսողի վրա։',
  },
  {
    functionId: 'fatica',
    title: 'Fática',
    formulaEs: 'Es fática porque comprueba o mantiene la comunicación.',
    formulaArm: 'Ֆատիկ է, որովհետև ստուգում կամ պահպանում է հաղորդակցությունը։',
  },
  {
    functionId: 'metalinguistica',
    title: 'Metalingüística',
    formulaEs: 'Es metalingüística porque habla sobre la lengua.',
    formulaArm: 'Մետալեզվական է, որովհետև խոսում է լեզվի մասին։',
  },
  {
    functionId: 'poetica',
    title: 'Poética',
    formulaEs: 'Es poética porque destaca la forma estética del mensaje.',
    formulaArm: 'Բանաստեղծական է, որովհետև կարևորում է հաղորդագրության գեղեցիկ ձևը։',
  },
];

export const EXAM_QUESTIONS_28: ExamQuestion[] = [
  {
    id: 1,
    spanish: '¿Qué función predomina en: “La Tierra gira alrededor del Sol”?',
    armenian: 'Ո՞ր գործառույթն է գերակշռում՝ «Երկիրը պտտվում է Արեգակի շուրջ»։',
    functionId: 'referencial',
    answerEs: 'Función referencial, porque transmite una información objetiva.',
    answerArm: 'Տեղեկատվական գործառույթ, որովհետև հաղորդում է օբյեկտիվ տեղեկություն։',
  },
  {
    id: 2,
    spanish: '“¡Estoy muy contento hoy!” ¿Qué función tiene?',
    armenian: '«Ես այսօր շատ ուրախ եմ»։ Ի՞նչ գործառույթ ունի։',
    functionId: 'expresiva',
    answerEs: 'Expresiva o emotiva, porque el emisor expresa un sentimiento.',
    answerArm: 'Զգացմունքային, որովհետև խոսողը արտահայտում է իր զգացմունքը։',
  },
  {
    id: 3,
    spanish: '“Cierra la puerta, por favor.”',
    armenian: '«Փակի՛ր դուռը, խնդրում եմ»։',
    functionId: 'apelativa',
    answerEs: 'Apelativa, porque intenta que el receptor haga algo.',
    answerArm: 'Դիմողական, որովհետև խոսողը ցանկանում է, որ լսողը որևէ գործողություն կատարի։',
  },
  {
    id: 4,
    spanish: '“¿Me escuchas?”',
    armenian: '«Ինձ լսո՞ւմ ես»։',
    functionId: 'fatica',
    answerEs: 'Fática, porque comprueba si la comunicación funciona.',
    answerArm: 'Ֆատիկ, որովհետև ստուգվում է՝ հաղորդակցությունն աշխատո՞ւմ է։',
  },
  {
    id: 5,
    spanish: '“‘Casa’ es un sustantivo.”',
    armenian: '«Casa բառը գոյական է»։',
    functionId: 'metalinguistica',
    answerEs: 'Metalingüística, porque usamos la lengua para hablar de la lengua.',
    answerArm: 'Մետալեզվական, որովհետև լեզուն օգտագործում ենք հենց լեզվի մասին խոսելու համար։',
  },
  {
    id: 6,
    spanish: '“Tus ojos son dos estrellas.”',
    armenian: '«Քո աչքերը երկու աստղ են»։',
    functionId: 'poetica',
    answerEs: 'Poética, porque importa la forma creativa y estética del mensaje.',
    answerArm: 'Բանաստեղծական, որովհետև կարևոր է խոսքի գեղեցիկ և ստեղծագործ ձևը։',
  },
  {
    id: 7,
    spanish: '“Mañana lloverá en Madrid.” ¿Qué función predomina?',
    armenian: '«Վաղը Մադրիդում անձրև է գալու»։',
    functionId: 'referencial',
    answerEs: 'Referencial, porque informa sobre un hecho.',
    answerArm: 'Տեղեկատվական, որովհետև տեղեկություն է հաղորդում։',
  },
  {
    id: 8,
    spanish: '“¡Qué frío hace!”',
    armenian: '«Ի՜նչ ցուրտ է»։',
    functionId: 'expresiva',
    answerEs: 'Expresiva, porque el hablante expresa su sensación.',
    answerArm: 'Զգացմունքային, որովհետև խոսողը արտահայտում է իր զգացողությունը։',
  },
  {
    id: 9,
    spanish: '“Estudia para el examen.”',
    armenian: '«Սովորի՛ր քննության համար»։',
    functionId: 'apelativa',
    answerEs: 'Apelativa, porque es una orden o consejo dirigido al receptor.',
    answerArm: 'Դիմողական, որովհետև դա լսողին ուղղված հրահանգ կամ խորհուրդ է։',
  },
  {
    id: 10,
    spanish: '“Hola, ¿qué tal?”',
    armenian: '«Բարև, ինչպե՞ս ես»։',
    functionId: 'fatica',
    answerEs: 'Fática, porque sirve para iniciar una conversación.',
    answerArm: 'Ֆատիկ, որովհետև օգտագործվում է խոսակցություն սկսելու համար։',
  },
  {
    id: 11,
    spanish: '“El verbo ‘comer’ pertenece a la segunda conjugación.”',
    armenian: '«Comer բայը պատկանում է երկրորդ խոնարհմանը»։',
    functionId: 'metalinguistica',
    answerEs: 'Metalingüística, porque estamos explicando una característica de una palabra.',
    answerArm: 'Մետալեզվական, որովհետև բացատրում ենք բառի լեզվական հատկանիշը։',
  },
  {
    id: 12,
    spanish: 'En un poema aparece: “La luna duerme sobre el mar”. ¿Qué función predomina?',
    armenian: 'Բանաստեղծության մեջ գրված է՝ «Լուսինը քնում է ծովի վրա»։ Ո՞ր գործառույթն է։',
    functionId: 'poetica',
    answerEs: 'Poética, porque el lenguaje se utiliza de forma artística.',
    answerArm: 'Բանաստեղծական, որովհետև լեզուն օգտագործվում է գեղարվեստական ձևով։',
  },
  {
    id: 13,
    spanish: '“El examen empieza a las nueve.”',
    armenian: '«Քննությունը սկսվում է ժամը իննին»։',
    functionId: 'referencial',
    answerEs: 'Referencial, porque comunica una información concreta.',
    answerArm: 'Տեղեկատվական, որովհետև հաղորդում է կոնկրետ տեղեկություն։',
  },
  {
    id: 14,
    spanish: '“¡No puedo creerlo! ¡Qué sorpresa!”',
    armenian: '«Չեմ կարող հավատալ։ Ի՜նչ անակնկալ»։',
    functionId: 'expresiva',
    answerEs: 'Expresiva, porque muestra la emoción del emisor.',
    answerArm: 'Զգացմունքային, որովհետև ցույց է տալիս խոսողի հույզը։',
  },
  {
    id: 15,
    spanish: '“No corráis por el pasillo.”',
    armenian: '«Միջանցքով մի՛ վազեք»։',
    functionId: 'apelativa',
    answerEs: 'Apelativa, porque pretende modificar el comportamiento del receptor.',
    answerArm: 'Դիմողական, որովհետև նպատակ ունի փոխել լսողի վարքը։',
  },
  {
    id: 16,
    spanish: 'Durante una llamada alguien dice: “¿Sí? ¿Sigues ahí?”',
    armenian: 'Հեռախոսազրույցի ժամանակ ասում են. «Այո՞։ Դեռ կապի մե՞ջ ես»։',
    functionId: 'fatica',
    answerEs: 'Fática, porque comprueba que el canal de comunicación sigue abierto.',
    answerArm: 'Ֆատիկ, որովհետև ստուգում է, որ հաղորդակցության կապը դեռ գործում է։',
  },
  {
    id: 17,
    spanish: '“Un sinónimo de ‘feliz’ es ‘contento’.”',
    armenian: '«Feliz բառի հոմանիշն է contento»։',
    functionId: 'metalinguistica',
    answerEs: 'Metalingüística, porque hablamos del significado y de las relaciones entre palabras.',
    answerArm: 'Մետալեզվական, որովհետև խոսում ենք բառերի իմաստի և հարաբերության մասին։',
  },
  {
    id: 18,
    spanish: 'Un anuncio dice: “¡Descubre un mundo de sabor!” ¿Qué función puede predominar?',
    armenian: 'Գովազդում գրված է՝ «Բացահայտի՛ր համի մի ամբողջ աշխարհ»։',
    functionId: 'apelativa',
    answerEs: 'Predomina la apelativa, porque intenta convencer al receptor. También tiene un elemento poético por su forma creativa.',
    answerArm: 'Գերակշռում է դիմողական գործառույթը, որովհետև փորձում է համոզել լսողին։ Միաժամանակ ունի նաև բանաստեղծական տարր։',
    note: {
      es: '⚠️ Pregunta con trampa: en un mensaje pueden coexistir varias funciones, pero debes identificar la predominante (función predominante).',
      arm: '⚠️ Թակարդ-հարց. մեկ հաղորդագրության մեջ կարող են լինել մի քանի գործառույթներ, սակայն քննությանը պետք է նշել գերակշռողը (función predominante):',
    },
  },
  {
    id: 19,
    spanish: '“Prohibido fumar.”',
    armenian: '«Ծխելն արգելվում է»։',
    functionId: 'apelativa',
    answerEs: 'Apelativa, porque pretende que las personas no fumen.',
    answerArm: 'Դիմողական, որովհետև նպատակն է, որ մարդիկ չծխեն։',
  },
  {
    id: 20,
    spanish: '“El agua está formada por hidrógeno y oxígeno.”',
    armenian: '«Ջուրը կազմված է ջրածնից և թթվածնից»։',
    functionId: 'referencial',
    answerEs: 'Referencial, porque transmite conocimiento objetivo.',
    answerArm: 'Տեղեկատվական, որովհետև հաղորդում է օբյեկտիվ գիտելիք։',
  },
  {
    id: 21,
    spanish: 'Un alumno dice: “No entiendo qué significa ‘nexo’”. ¿Qué función aparece principalmente?',
    armenian: 'Աշակերտն ասում է. «Չեմ հասկանում, թե ինչ է նշանակում nexo բառը»։',
    functionId: 'metalinguistica',
    answerEs: 'Metalingüística, porque pregunta por el significado de una palabra.',
    answerArm: 'Մետալեզվական, որովհետև հարցնում է բառի նշանակության մասին։',
  },
  {
    id: 22,
    spanish: '“Ojalá ganemos el partido.”',
    armenian: '«Երանի հաղթենք խաղը»։',
    functionId: 'expresiva',
    answerEs: 'Expresiva, porque manifiesta un deseo del hablante.',
    answerArm: 'Զգացմունքային, որովհետև խոսողն արտահայտում է իր ցանկությունը։',
  },
  {
    id: 23,
    spanish: 'El profesor pregunta: “¿Habéis entendido?”',
    armenian: 'Ուսուցիչը հարցնում է. «Հասկացե՞լ եք»։',
    functionId: 'fatica',
    answerEs: 'Puede predominar la fática si comprueba que la comunicación ha funcionado.',
    answerArm: 'Կարող է գերակշռել ֆատիկ գործառույթը, եթե ուսուցիչը ստուգում է՝ հաղորդակցությունը հասկանալի եղե՞լ է։',
  },
  {
    id: 24,
    spanish: '¿Cuál es la diferencia principal entre función referencial y expresiva?',
    armenian: 'Ո՞րն է հիմնական տարբերությունը տեղեկատվական և զգացմունքային գործառույթների միջև։',
    isTheoretical: true,
    answerEs: 'La referencial se centra en la información y la realidad; la expresiva se centra en los sentimientos u opiniones del emisor.',
    answerArm: 'Տեղեկատվականը կենտրոնանում է փաստերի և տեղեկության վրա, իսկ զգացմունքայինը՝ խոսողի զգացմունքների և կարծիքի վրա։',
  },
  {
    id: 25,
    spanish: '¿Cuál es la diferencia entre apelativa y fática?',
    armenian: 'Ո՞րն է տարբերությունը դիմողական և ֆատիկ գործառույթների միջև։',
    isTheoretical: true,
    answerEs: 'La apelativa intenta que el receptor actúe; la fática sirve para iniciar, mantener o comprobar la comunicación.',
    answerArm: 'Դիմողականը փորձում է լսողին գործողության դրդել, իսկ ֆատիկը սկսում, պահպանում կամ ստուգում է հաղորդակցությունը։',
  },
  {
    id: 26,
    spanish: '¿Cómo sabes que una oración tiene función metalingüística?',
    armenian: 'Ինչպե՞ս հասկանալ, որ նախադասությունն ունի մետալեզվական գործառույթ։',
    isTheoretical: true,
    answerEs: 'Porque el mensaje habla de palabras, significados, gramática o de la propia lengua.',
    answerArm: 'Որովհետև խոսքը վերաբերում է բառերին, դրանց իմաստին, քերականությանը կամ հենց լեզվին։',
  },
  {
    id: 27,
    spanish: '¿Puede una oración tener más de una función?',
    armenian: 'Կարո՞ղ է մեկ նախադասությունը ունենալ մեկից ավելի գործառույթ։',
    isTheoretical: true,
    answerEs: 'Sí. Puede haber varias funciones, pero normalmente una es la predominante.',
    answerArm: 'Այո։ Կարող են լինել մի քանի գործառույթներ, բայց սովորաբար դրանցից մեկը գերակշռողն է։',
  },
  {
    id: 28,
    spanish: 'En un examen te preguntan: “Justifica tu respuesta”. ¿Qué debes hacer?',
    armenian: 'Քննության ժամանակ հարցնում են՝ «Justifica tu respuesta»։ Ի՞նչ պետք է անել։',
    isTheoretical: true,
    answerEs: 'Respuesta modelo: “Es una función expresiva porque el emisor expresa sus sentimientos.” (Nunca escribir solo una palabra; siempre usar la fórmula completa).',
    answerArm: 'Օրինակելի պատասխան. «Սա զգացմունքային գործառույթ է, որովհետև խոսողն արտահայտում է իր զգացմունքները։» (Երբեք միայն մեկ բառ չգրել, միշտ ամբողջական բանաձևով)։',
  },
];

export const TEXT_STUDY_UNITS: TextStudyUnit[] = [
  // Texto 1 — En clase
  {
    id: 'texto-1-clase',
    number: 1,
    series: 'primera',
    titleEs: 'Texto 1 — En clase',
    titleArm: 'Տեքստ 1 — Դասարանում',
    subtitleEs: 'Diálogo escolar y análisis de funciones',
    subtitleArm: 'Դպրոցական երկխոսություն և գործառույթների վերլուծություն',
    badge: 'Básico',
    dialogue: [
      {
        speaker: 'Narrador',
        es: 'La profesora entra en clase y dice:',
        arm: 'Ուսուցչուհին մտնում է դասարան և ասում է․',
      },
      {
        speaker: 'Profesora',
        es: '—Buenos días. ¿Me escucháis bien?',
        arm: '— Բարի լույս։ Ինձ լա՞վ եք լսում։',
        functionId: 'fatica',
        boldPhraseEs: '¿Me escucháis bien?',
        boldPhraseArm: 'Ինձ լա՞վ եք լսում։',
      },
      {
        speaker: 'Alumnos',
        es: '—Sí —responden los alumnos.',
        arm: '— Այո՛,— պատասխանում են աշակերտները։',
      },
      {
        speaker: 'Narrador',
        es: 'La profesora continúa:',
        arm: 'Ուսուցչուհին շարունակում է․',
      },
      {
        speaker: 'Profesora',
        es: '—Hoy vamos a estudiar las funciones del lenguaje. Primero, abrid el libro por la página 35.',
        arm: '— Այսօր ուսումնասիրելու ենք լեզվի գործառույթները։ Սկզբում բացե՛ք գիրքը 35-րդ էջում։',
        boldPhraseEs: 'Hoy vamos a estudiar las funciones del lenguaje. Primero, abrid el libro por la página 35.',
        boldPhraseArm: 'Այսօր ուսումնասիրելու ենք լեզվի գործառույթները։ Սկզբում բացե՛ք գիրքը 35-րդ էջում։',
      },
      {
        speaker: 'Narrador',
        es: 'Pablo mira el ejercicio y dice:',
        arm: 'Պաբլոն նայում է վարժությանը և ասում․',
      },
      {
        speaker: 'Pablo',
        es: '—¡Qué difícil parece este tema!',
        arm: '— Ի՜նչ դժվար է թվում այս թեման։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Qué difícil parece este tema!',
        boldPhraseArm: 'Ի՜նչ դժվար է թվում այս թեման։',
      },
      {
        speaker: 'Narrador',
        es: 'La profesora sonríe y explica:',
        arm: 'Ուսուցչուհին ժպտում է և բացատրում․',
      },
      {
        speaker: 'Profesora',
        es: '—No os preocupéis. Un sustantivo es una palabra que sirve para nombrar personas, animales, lugares, objetos o ideas.',
        arm: '— Մի՛ անհանգստացեք։ Գոյականը բառ է, որն օգտագործվում է մարդկանց, կենդանիների, վայրերի, առարկաների կամ գաղափարների անվանման համար։',
        functionId: 'metalinguistica',
        boldPhraseEs: 'Un sustantivo es una palabra que sirve para nombrar personas, animales, lugares, objetos o ideas.',
        boldPhraseArm: 'Գոյականը բառ է, որն օգտագործվում է մարդկանց, կենդանիների, վայրերի, առարկաների կամ գաղափարների անվանման համար։',
      },
      {
        speaker: 'Narrador',
        es: 'Después escribe en la pizarra:',
        arm: 'Այնուհետև գրատախտակին գրում է․',
      },
      {
        speaker: 'Profesora',
        es: '—“Tus ojos brillan como estrellas.”',
        arm: '— «Քո աչքերը փայլում են աստղերի պես»։',
        functionId: 'poetica',
        boldPhraseEs: '“Tus ojos brillan como estrellas.”',
        boldPhraseArm: '«Քո աչքերը փայլում են աստղերի պես»։',
      },
      {
        speaker: 'Narrador',
        es: 'Y pregunta: —¿Qué función del lenguaje encontráis aquí? Antes de terminar la clase dice:',
        arm: 'Եվ հարցնում է․ — Ի՞նչ գործառույթ եք տեսնում այստեղ։ Դասի վերջում ասում է․',
      },
      {
        speaker: 'Profesora',
        es: '—Recordad estudiar para el examen del martes.',
        arm: '— Հիշե՛ք սովորել երեքշաբթի օրվա քննության համար։',
        functionId: 'apelativa',
        boldPhraseEs: 'Recordad estudiar para el examen del martes.',
        boldPhraseArm: 'Հիշե՛ք սովորել երեքշաբթի օրվա քննության համար։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: '¿Qué función aparece en “¿Me escucháis bien?”',
        questionArm: '«Ինձ լա՞վ եք լսում» նախադասության մեջ ո՞ր գործառույթն է։',
        answerEs: 'Fática, porque comprueba si funciona la comunicación.',
        answerArm: 'Ֆատիկ, որովհետև ստուգվում է՝ հաղորդակցությունն աշխատո՞ւմ է։',
      },
      {
        id: 2,
        questionEs: '¿Qué función predomina en “Hoy vamos a estudiar las funciones del lenguaje”?',
        questionArm: '«Այսօր ուսումնասիրելու ենք լեզվի գործառույթները» նախադասության մեջ ո՞րն է գերակշռում։',
        answerEs: 'Referencial, porque comunica información sobre la clase.',
        answerArm: 'Տեղեկատվական, որովհետև տեղեկություն է հաղորդում դասի մասին։',
      },
      {
        id: 3,
        questionEs: '¿Qué función tiene “Abrid el libro por la página 35”?',
        questionArm: 'Ի՞նչ գործառույթ ունի «Բացե՛ք գիրքը 35-րդ էջում» նախադասությունը։',
        answerEs: 'Apelativa, porque la profesora quiere que los alumnos hagan algo.',
        answerArm: 'Դիմողական, որովհետև ուսուցչուհին ուզում է, որ աշակերտները գործողություն կատարեն։',
      },
      {
        id: 4,
        questionEs: '“¡Qué difícil parece este tema!” → ¿qué función?',
        questionArm: '«Ի՜նչ դժվար է թվում այս թեման» → ո՞ր գործառույթն է։',
        answerEs: 'Expresiva, porque Pablo expresa lo que siente.',
        answerArm: 'Զգացմունքային, որովհետև Պաբլոն արտահայտում է իր զգացողությունը։',
      },
      {
        id: 5,
        questionEs: '¿Por qué la explicación de “sustantivo” es metalingüística?',
        questionArm: 'Ինչո՞ւ «գոյական» (sustantivo) բառի բացատրությունը մետալեզվական է։',
        answerEs: 'Porque utiliza la lengua para explicar una palabra y una categoría gramatical.',
        answerArm: 'Որովհետև լեզուն օգտագործվում է բառ և քերականական կարգ բացատրելու համար։',
      },
      {
        id: 6,
        questionEs: '¿Qué función predomina en “Tus ojos brillan como estrellas”?',
        questionArm: 'Ո՞ր գործառույթն է գերակշռում «Քո աչքերը փայլում են աստղերի պես» նախադասության մեջ։',
        answerEs: 'Poética, porque destaca la forma artística del mensaje.',
        answerArm: 'Բանաստեղծական, որովհետև կարևորվում է արտահայտության գեղարվեստական ձևը։',
      },
      {
        id: 7,
        questionEs: '“Recordad estudiar para el examen” es…',
        questionArm: '«Հիշե՛ք սովորել քննության համար» նախադասությունը…',
        answerEs: 'Apelativa, porque intenta influir en el comportamiento de los alumnos.',
        answerArm: 'Դիմողական, որովհետև ուսուցչուհին ցանկանում է ազդել աշակերտների գործողության վրա։',
      },
    ],
  },

  // Texto 2 — En una tienda
  {
    id: 'texto-2-tienda',
    number: 2,
    series: 'primera',
    titleEs: 'Texto 2 — En una tienda',
    titleArm: 'Տեքստ 2 — Խանութում',
    subtitleEs: 'Compras, publicidad y lenguaje publicitario',
    subtitleArm: 'Գնումներ, գովազդ և գովազդային լեզու',
    badge: 'Publicidad',
    dialogue: [
      {
        speaker: 'Carla',
        es: '—Hola, buenos días.',
        arm: '— Բարև, բարի օր։',
      },
      {
        speaker: 'Dependienta',
        es: '—Buenos días. ¿En qué puedo ayudarte?',
        arm: '— Բարի օր։ Ինչո՞վ կարող եմ օգնել։',
        functionId: 'fatica',
      },
      {
        speaker: 'Carla',
        es: '—¡Me encanta esta chaqueta!',
        arm: '— Ես շա՜տ եմ հավանում այս բաճկոնը։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Me encanta esta chaqueta!',
        boldPhraseArm: 'Ես շա՜տ եմ հավանում այս բաճկոնը։',
      },
      {
        speaker: 'Dependienta',
        es: '—Esta chaqueta cuesta 45 euros y está disponible en tres colores.',
        arm: '— Այս բաճկոնն արժե 45 եվրո և կա երեք գույնով։',
        functionId: 'referencial',
        boldPhraseEs: 'Esta chaqueta cuesta 45 euros y está disponible en tres colores.',
        boldPhraseArm: 'Այս բաճկոնն արժե 45 եվրո և կա երեք գույնով։',
      },
      {
        speaker: 'Carla',
        es: '—¿Tiene una talla más grande?',
        arm: '— Ավելի մեծ չափ կա՞։',
      },
      {
        speaker: 'Dependienta',
        es: '—Sí. Espera aquí un momento, por favor.',
        arm: '— Այո՛։ Խնդրում եմ, մի պահ սպասի՛ր այստեղ։',
        functionId: 'apelativa',
        boldPhraseEs: 'Espera aquí un momento, por favor.',
        boldPhraseArm: 'Խնդրում եմ, մի պահ սպասի՛ր այստեղ։',
      },
      {
        speaker: 'Narrador',
        es: 'Mientras espera, Carla ve un cartel: “Viste tus sueños. Descubre tu propio estilo.”',
        arm: 'Սպասելիս Կառլան տեսնում է գովազդային պաստառ․ «Հագի՛ր քո երազանքները։ Բացահայտի՛ր քո սեփական ոճը»։',
        boldPhraseEs: '“Viste tus sueños. Descubre tu propio estilo.”',
        boldPhraseArm: '«Հագի՛ր քո երազանքները։ Բացահայտի՛ր քո սեփական ոճը»։',
      },
      {
        speaker: 'Carla',
        es: '—Por cierto, ¿qué significa la palabra “rebaja”?',
        arm: '— Ի դեպ, ի՞նչ է նշանակում rebaja բառը։',
        functionId: 'metalinguistica',
        boldPhraseEs: '¿qué significa la palabra “rebaja”?',
        boldPhraseArm: 'ի՞նչ է նշանակում rebaja բառը։',
      },
      {
        speaker: 'Dependienta',
        es: '—Una rebaja es una reducción del precio original de un producto.',
        arm: '— Rebaja-ն ապրանքի սկզբնական գնի նվազեցումն է։',
        functionId: 'metalinguistica',
        boldPhraseEs: 'Una rebaja es una reducción del precio original de un producto.',
        boldPhraseArm: 'Rebaja-ն ապրանքի սկզբնական գնի նվազեցումն է։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: '“¡Me encanta esta chaqueta!” →',
        questionArm: '«¡Me encanta esta chaqueta!» →',
        answerEs: 'Expresiva. Expresa un gusto o sentimiento.',
        answerArm: 'Զգացմունքային։ Արտահայտում է հավանություն կամ զգացում։',
      },
      {
        id: 2,
        questionEs: '“Esta chaqueta cuesta 45 euros…” →',
        questionArm: '«Esta chaqueta cuesta 45 euros…» →',
        answerEs: 'Referencial, porque proporciona información concreta.',
        answerArm: 'Տեղեկատվական, որովհետև հաղորդում է կոնկրետ տեղեկություն։',
      },
      {
        id: 3,
        questionEs: '“Espera aquí un momento” →',
        questionArm: '«Espera aquí un momento» →',
        answerEs: 'Apelativa.',
        answerArm: 'Դիմողական։',
      },
      {
        id: 4,
        questionEs: '“¿Qué significa la palabra ‘rebaja’?” →',
        questionArm: '«¿Qué significa la palabra ‘rebaja’?» →',
        answerEs: 'Metalingüística, porque se pregunta por el significado de una palabra.',
        answerArm: 'Մետալեզվական, որովհետև հարց է տրվում բառի իմաստի մասին։',
      },
      {
        id: 5,
        questionEs: 'La definición de “rebaja” →',
        questionArm: '«Rebaja» բառի սահմանումը →',
        answerEs: 'Metalingüística.',
        answerArm: 'Մետալեզվական։',
      },
      {
        id: 6,
        questionEs: '“Viste tus sueños. Descubre tu propio estilo.” ¿Tiene una sola función?',
        questionArm: '«Հագի՛ր քո երազանքները։ Բացահայտի՛ր քո սեփական ոճը» արտահայտությունն ունի՞ միայն մեկ գործառույթ։',
        answerEs: 'No necesariamente. Tiene función apelativa, porque intenta convencer al receptor, y también un componente poético, porque utiliza una expresión creativa. (Nota: si en el examen preguntan función predominante, aquí se elige apelativa por su finalidad publicitaria).',
        answerArm: 'Ոչ պարտադիր։ Այստեղ կա դիմողական գործառույթ, որովհետև գովազդը փորձում է ազդել մարդու վրա, և նաև բանաստեղծական տարր, որովհետև օգտագործվում է ստեղծագործ արտահայտություն։ (Քննության նշում՝ եթե հարցնում են գերակշռողը, ապա ընտրում ենք դիմողականը/apelativa):',
      },
    ],
    tip: {
      es: '⭐ Si en el examen preguntan función predominante, aquí es mejor elegir apelativa por la finalidad publicitaria de la frase.',
      arm: '⭐ Եթե քննությանը հարցնում են գերակշռող գործառույթը (función predominante), գովազդային նպատակի պատճառով ճիշտ է նշել դիմողական (apelativa):',
    },
  },

  // Texto 3 — Antes de un partido (Test format)
  {
    id: 'texto-3-partido',
    number: 3,
    series: 'primera',
    titleEs: 'Texto 3 — Antes de un partido',
    titleArm: 'Տեքստ 3 — Ֆուտբոլային խաղից առաջ',
    subtitleEs: 'Test tipo examen con opciones múltiples',
    subtitleArm: 'Քննական տիպի թեստ բազմակի ընտրությամբ',
    badge: 'Test con opciones',
    dialogue: [
      {
        speaker: 'Narrador',
        es: 'Los jugadores están en el vestuario antes de un partido.',
        arm: 'Ֆուտբոլիստները խաղից առաջ հանդերձարանում են։',
      },
      {
        speaker: 'Entrenador',
        es: '—¿Todos me escucháis?',
        arm: '— Բոլորդ ինձ լսո՞ւմ եք։',
        functionId: 'fatica',
        boldPhraseEs: '¿Todos me escucháis?',
        boldPhraseArm: 'Բոլորդ ինձ լսո՞ւմ եք։',
      },
      {
        speaker: 'Jugadores',
        es: '—Sí.',
        arm: '— Այո՛։',
      },
      {
        speaker: 'Entrenador',
        es: '—El partido empieza a las cinco y tenemos noventa minutos para demostrar nuestro nivel.',
        arm: '— Խաղը սկսվում է ժամը հինգին, և մենք ունենք իննսուն րոպե՝ մեր մակարդակը ցույց տալու համար։',
        functionId: 'referencial',
        boldPhraseEs: 'El partido empieza a las cinco y tenemos noventa minutos...',
        boldPhraseArm: 'Խաղը սկսվում է ժամը հինգին, և մենք ունենք իննսուն րոպե…',
      },
      {
        speaker: 'Jugador',
        es: '—¡Estoy muy nervioso!',
        arm: '— Ես շատ նյարդայնացած եմ։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Estoy muy nervioso!',
        boldPhraseArm: 'Ես շատ նյարդայնացած եմ։',
      },
      {
        speaker: 'Entrenador',
        es: '—No pasa nada. Confía en tus compañeros, juega con calma y no pierdas la concentración.',
        arm: '— Ոչինչ։ Վստահի՛ր թիմակիցներիդ, հանգիստ խաղա՛ և մի՛ կորցրու կենտրոնացումը։',
        functionId: 'apelativa',
        boldPhraseEs: 'Confía en tus compañeros, juega con calma y no pierdas la concentración.',
        boldPhraseArm: 'Վստահի՛ր թիմակիցներիդ, հանգիստ խաղա՛ և մի՛ կորցրու կենտրոնացումը։',
      },
      {
        speaker: 'Otro jugador',
        es: '—Profe, ¿qué significa exactamente “concentración”?',
        arm: '— Մարզիչ, իսկ ի՞նչ է նշանակում concentración բառը։',
        functionId: 'metalinguistica',
      },
      {
        speaker: 'Entrenador',
        es: '—“Concentración” significa mantener la atención en lo que estás haciendo.',
        arm: '— Concentración նշանակում է ուշադրությունը պահել այն բանի վրա, ինչ անում ես։',
        functionId: 'metalinguistica',
        boldPhraseEs: '“Concentración” significa mantener la atención...',
        boldPhraseArm: 'Concentración նշանակում է ուշադրությունը պահել…',
      },
      {
        speaker: 'Entrenador',
        es: '—Hoy el balón tiene que escuchar nuestros sueños.',
        arm: '— Այսօր գնդակը պետք է լսի մեր երազանքները։',
        functionId: 'poetica',
        boldPhraseEs: 'Hoy el balón tiene que escuchar nuestros sueños.',
        boldPhraseArm: 'Այսօր գնդակը պետք է լսի մեր երազանքները։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: '¿Qué función tiene “¿Todos me escucháis?”',
        questionArm: 'Ի՞նչ գործառույթ ունի «¿Todos me escucháis?» նախադասությունը։',
        options: [
          { key: 'a', text: 'Expresiva', isCorrect: false },
          { key: 'b', text: 'Fática', isCorrect: true },
          { key: 'c', text: 'Poética', isCorrect: false },
          { key: 'd', text: 'Referencial', isCorrect: false },
        ],
        answerEs: 'b) Fática — Comprueba el contacto con los receptores.',
        answerArm: 'b) Ֆատիկ — Ստուգում է՝ լսողները լսո՞ւմ են իրեն։',
      },
      {
        id: 2,
        questionEs: '“El partido empieza a las cinco…”',
        questionArm: '«El partido empieza a las cinco…»',
        options: [
          { key: 'a', text: 'Referencial', isCorrect: true },
          { key: 'b', text: 'Poética', isCorrect: false },
          { key: 'c', text: 'Expresiva', isCorrect: false },
          { key: 'd', text: 'Metalingüística', isCorrect: false },
        ],
        answerEs: 'a) Referencial — Comunica información objetiva.',
        answerArm: 'a) Տեղեկատվական — Տեղեկություն է հաղորդում։',
      },
      {
        id: 3,
        questionEs: '“¡Estoy muy nervioso!”',
        questionArm: '«¡Estoy muy nervioso!»',
        options: [
          { key: 'a', text: 'Fática', isCorrect: false },
          { key: 'b', text: 'Referencial', isCorrect: false },
          { key: 'c', text: 'Expresiva', isCorrect: true },
          { key: 'd', text: 'Apelativa', isCorrect: false },
        ],
        answerEs: 'c) Expresiva — El futbolista expresa su sentimiento.',
        answerArm: 'c) Զգացմունքային — Ֆուտբոլիստն արտահայտում է իր զգացմունքը։',
      },
      {
        id: 4,
        questionEs: '“Confía…, juega…, no pierdas…”',
        questionArm: '«Confía…, juega…, no pierdas…»',
        options: [
          { key: 'a', text: 'Poética', isCorrect: false },
          { key: 'b', text: 'Apelativa', isCorrect: true },
          { key: 'c', text: 'Fática', isCorrect: false },
          { key: 'd', text: 'Referencial', isCorrect: false },
        ],
        answerEs: 'b) Apelativa — El entrenador da órdenes y consejos al receptor.',
        answerArm: 'b) Դիմողական — Մարզիչը հրահանգներ և խորհուրդներ է տալիս։',
      },
      {
        id: 5,
        questionEs: '¿Qué función aparece cuando preguntan qué significa “concentración”?',
        questionArm: 'Ո՞ր գործառույթն է ի հայտ գալիս, երբ հարցնում են «concentración» բառի իմաստը։',
        options: [
          { key: 'a', text: 'Referencial', isCorrect: false },
          { key: 'b', text: 'Expresiva', isCorrect: false },
          { key: 'c', text: 'Metalingüística', isCorrect: true },
          { key: 'd', text: 'Fática', isCorrect: false },
        ],
        answerEs: 'c) Metalingüística — La pregunta se refiere al significado de una palabra.',
        answerArm: 'c) Մետալեզվական — Հարցը վերաբերում է բառի նշանակությանը։',
      },
      {
        id: 6,
        questionEs: '“Hoy el balón tiene que escuchar nuestros sueños.”',
        questionArm: '«Hoy el balón tiene que escuchar nuestros sueños.»',
        options: [
          { key: 'a', text: 'Poética', isCorrect: true },
          { key: 'b', text: 'Fática', isCorrect: false },
          { key: 'c', text: 'Metalingüística', isCorrect: false },
          { key: 'd', text: 'Referencial', isCorrect: false },
        ],
        answerEs: 'a) Poética — Se utiliza una expresión figurativa y artística.',
        answerArm: 'a) Բանաստեղծական — Օգտագործվում է պատկերավոր և ստեղծագործ արտահայտություն։',
      },
    ],
  },

  // Texto 4 — Más difícil, tipo examen
  {
    id: 'texto-4-dificil',
    number: 4,
    series: 'primera',
    titleEs: 'Texto 4 — Más difícil, tipo examen',
    titleArm: 'Տեքստ 4 — Ավելի դժվար՝ քննության նման',
    subtitleEs: 'Análisis profundo con emisores, receptores y justificación',
    subtitleArm: 'Խորացված վերլուծություն՝ հաղորդող, ընդունող և հիմնավորում',
    badge: 'Avanzado',
    dialogue: [
      {
        speaker: 'Ana',
        es: '—¿Hola? Marta, ¿sigues ahí?',
        arm: '— Ալո՞։ Մարտա, դեռ կապի մե՞ջ ես։',
        functionId: 'fatica',
        boldPhraseEs: '¿Hola? Marta, ¿sigues ahí?',
        boldPhraseArm: 'Ալո՞։ Մարտա, դեռ կապի մե՞ջ ես։',
      },
      {
        speaker: 'Marta',
        es: '—Sí, te escucho.',
        arm: '— Այո, լսում եմ քեզ։',
      },
      {
        speaker: 'Ana',
        es: '—Mañana el museo abre a las diez. ¿Vamos juntas?',
        arm: '— Վաղը թանգարանը բացվում է ժամը տասին։ Միասի՞ն գնանք։',
        functionId: 'referencial',
        boldPhraseEs: 'Mañana el museo abre a las diez.',
        boldPhraseArm: 'Վաղը թանգարանը բացվում է ժամը տասին։',
      },
      {
        speaker: 'Marta',
        es: '—¡Qué buena idea! Me encanta ese museo.',
        arm: '— Ի՜նչ լավ միտք է։ Ես շատ եմ սիրում այդ թանգարանը։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Qué buena idea! Me encanta ese museo.',
        boldPhraseArm: 'Ի՜նչ լավ միտք է։ Ես շատ եմ սիրում այդ թանգարանը։',
      },
      {
        speaker: 'Ana',
        es: '—Entonces compra las entradas esta tarde, por favor.',
        arm: '— Ուրեմն տոմսերը գնի՛ր այսօր կեսօրից հետո, խնդրում եմ։',
        functionId: 'apelativa',
        boldPhraseEs: 'compra las entradas esta tarde, por favor.',
        boldPhraseArm: 'տոմսերը գնի՛ր այսօր կեսօրից հետո, խնդրում եմ։',
      },
      {
        speaker: 'Marta',
        es: '—Vale. Por cierto, en la página del museo aparece la palabra exposición. ¿Qué significa exactamente?',
        arm: '— Լավ։ Ի դեպ, թանգարանի կայքում գրված է exposición բառը։ Ի՞նչ է նշանակում։',
      },
      {
        speaker: 'Ana',
        es: '—Una exposición es una presentación pública de obras u objetos.',
        arm: '— Ցուցահանդեսը (exposición) ստեղծագործությունների կամ առարկաների հրապարակային ցուցադրությունն է։',
        functionId: 'metalinguistica',
        boldPhraseEs: 'Una exposición es una presentación pública de obras u objetos.',
        boldPhraseArm: 'Ցուցահանդեսը (exposición) ստեղծագործությունների կամ առարկաների հրապարակային ցուցադրությունն է։',
      },
      {
        speaker: 'Narrador',
        es: 'Ana lee después un anuncio del museo: “Viaja al pasado sin salir de la ciudad.”',
        arm: 'Անան հետո կարդում է թանգարանի գովազդը․ «Ճամփորդի՛ր դեպի անցյալ՝ առանց քաղաքից դուրս գալու»։',
        boldPhraseEs: '“Viaja al pasado sin salir de la ciudad.”',
        boldPhraseArm: '«Ճամփորդի՛ր դեպի անցյալ՝ առանց քաղաքից դուրս գալու»։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: '¿Sigues ahí? → ¿__________?',
        questionArm: '«¿Sigues ahí?» → ո՞ր գործառույթն է։',
        answerEs: 'Fática',
        answerArm: 'Ֆատիկ (comprueba el canal de comunicación)',
      },
      {
        id: 2,
        questionEs: 'Mañana el museo abre a las diez. → ¿__________?',
        questionArm: '«Mañana el museo abre a las diez.» → ո՞ր գործառույթն է։',
        answerEs: 'Referencial',
        answerArm: 'Տեղեկատվական (transmite información objetiva)',
      },
      {
        id: 3,
        questionEs: '¡Qué buena idea! → ¿__________?',
        questionArm: '«¡Qué buena idea!» → ո՞ր գործառույթն է։',
        answerEs: 'Expresiva',
        answerArm: 'Զգացմունքային (expresa valoración personal)',
      },
      {
        id: 4,
        questionEs: 'Compra las entradas. → ¿__________?',
        questionArm: '«Compra las entradas.» → ո՞ր գործառույթն է։',
        answerEs: 'Apelativa',
        answerArm: 'Դիմողական (pide una acción al receptor)',
      },
      {
        id: 5,
        questionEs: 'Explicar “exposición” → ¿__________?',
        questionArm: '«Exposición» բառի բացատրությունը → ո՞ր գործառույթն է։',
        answerEs: 'Metalingüística',
        answerArm: 'Մետալեզվական (define el significado de una palabra)',
      },
      {
        id: 6,
        questionEs: '“Viaja al pasado sin salir de la ciudad.” → ¿qué dos funciones pueden aparecer?',
        questionArm: '«Viaja al pasado sin salir de la ciudad.» → ո՞ր երկու գործառույթները կարող են լինել։',
        answerEs: 'Poética + apelativa',
        answerArm: 'Բանաստեղծական + դիմողական (poética + apelativa)',
      },
      {
        id: 7,
        questionEs: '¿Cuál sería la función predominante si esa frase aparece en un anuncio?',
        questionArm: 'Ո՞րն է գերակշռող գործառույթը, եթե այդ նախադասությունը հանդիպում է գովազդում։',
        answerEs: 'Apelativa, porque el anuncio intenta atraer o convencer al receptor.',
        answerArm: 'Դիմողական, որովհետև գովազդը փորձում է գրավել կամ համոզել մարդուն։',
      },
      {
        id: 8,
        questionEs: '¿Quién es el emisor cuando Ana dice “Mañana el museo abre a las diez”?',
        questionArm: 'Ո՞վ է հաղորդողը (emisor), երբ Անան ասում է «Mañana el museo abre a las diez»։',
        answerEs: 'Ana es la emisora.',
        answerArm: 'Անան հաղորդողն է (Ana es la emisora)։',
      },
      {
        id: 9,
        questionEs: '¿Quién es el receptor?',
        questionArm: 'Ո՞վ է ընդունողը (receptor)։',
        answerEs: 'Marta es la receptora.',
        answerArm: 'Մարտան ընդունողն է (Marta es la receptora)։',
      },
      {
        id: 10,
        questionEs: 'Explica en español por qué “¡Qué buena idea!” no es referencial.',
        questionArm: 'Բացատրի՛ր իսպաներեն, թե ինչու «¡Qué buena idea!» նախադասությունը տեղեկատվական (referencial) չէ։',
        answerEs: 'Porque Ana no comunica un hecho objetivo; expresa su valoración y entusiasmo personal.',
        answerArm: 'Որովհետև Անան օբյեկտիվ փաստ չի հաղորդում, այլ արտահայտում է իր վերաբերմունքն ու ոգևորությունը։',
      },
    ],
  },

  // Texto 5 (Texto 1 bis) — En clase antes del examen
  {
    id: 'texto-1-bis-examen',
    number: 5,
    series: 'segunda',
    titleEs: 'Texto 1 — En clase antes del examen',
    titleArm: 'Տեքստ 1 — Դասարանում՝ քննությունից առաջ',
    subtitleEs: '“Busca tú mismo”: localiza ejemplos en el texto',
    subtitleArm: '«Գտի՛ր ինքդ». գտիր համապատասխան նախադասությունը',
    badge: 'Busca tú mismo',
    dialogue: [
      {
        speaker: 'Profesor',
        es: '—¿Me oís bien desde el fondo?',
        arm: '— Վերջին նստարանից ինձ լա՞վ եք լսում։',
        functionId: 'fatica',
        boldPhraseEs: '¿Me oís bien desde el fondo?',
        boldPhraseArm: 'Վերջին նստարանից ինձ լա՞վ եք լսում։',
      },
      {
        speaker: 'Narrador',
        es: 'Los alumnos responden que sí. Entonces el profesor continúa:',
        arm: 'Աշակերտները պատասխանում են՝ այո։ Այնուհետև ուսուցիչը շարունակում է․',
      },
      {
        speaker: 'Profesor',
        es: '—Mañana tenemos el examen de Lengua a las nueve. Hoy vamos a hacer un último repaso.',
        arm: '— Վաղը ժամը իննին Լեզվի քննություն ունենք։ Այսօր վերջին անգամ կրկնելու ենք նյութը։',
        functionId: 'referencial',
        boldPhraseEs: 'Mañana tenemos el examen de Lengua a las nueve.',
        boldPhraseArm: 'Վաղը ժամը իննին Լեզվի քննություն ունենք։',
      },
      {
        speaker: 'Daniel',
        es: '—¡Estoy muy nervioso por el examen!',
        arm: '— Ես շա՜տ եմ անհանգստանում քննության պատճառով։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Estoy muy nervioso por el examen!',
        boldPhraseArm: 'Ես շա՜տ եմ անհանգստանում քննության պատճառով։',
      },
      {
        speaker: 'Profesor',
        es: '—Tranquilo. Repasad las funciones del lenguaje y leed bien cada pregunta antes de responder.',
        arm: '— Հանգիստ։ Կրկնե՛ք լեզվի գործառույթները և յուրաքանչյուր հարց լավ կարդացե՛ք պատասխանելուց առաջ։',
        functionId: 'apelativa',
        boldPhraseEs: 'Repasad las funciones del lenguaje y leed bien cada pregunta antes de responder.',
        boldPhraseArm: 'Կրկնե՛ք լեզվի գործառույթները և յուրաքանչյուր հարց լավ կարդացե՛ք պատասխանելուց առաջ։',
      },
      {
        speaker: 'Profesor',
        es: '—“Rápidamente” es un adverbio.',
        arm: '— «Rápidamente» բառը մակբայ է։',
        functionId: 'metalinguistica',
        boldPhraseEs: '“Rápidamente” es un adverbio.',
        boldPhraseArm: '«Rápidamente» բառը մակբայ է։',
      },
      {
        speaker: 'Profesor',
        es: '—“Las palabras pueden abrir puertas que las llaves no pueden abrir.”',
        arm: '— «Բառերը կարող են բացել այնպիսի դռներ, որոնք բանալիները չեն կարող բացել»։',
        functionId: 'poetica',
        boldPhraseEs: '“Las palabras pueden abrir puertas que las llaves no pueden abrir.”',
        boldPhraseArm: '«Բառերը կարող են բացել այնպիսի դռներ, որոնք բանալիները չեն կարող բացել»։',
      },
      {
        speaker: 'Profesor',
        es: '—¿Podéis encontrar aquí diferentes funciones del lenguaje?',
        arm: '— Կարո՞ղ եք այստեղ գտնել լեզվի տարբեր գործառույթներ։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: 'Busca un ejemplo de función fática.',
        questionArm: 'Գտի՛ր ֆատիկ գործառույթի օրինակ։',
        answerEs: '“¿Me oís bien desde el fondo?” (Comprueba si funciona el canal).',
        answerArm: '«¿Me oís bien desde el fondo?» — Ստուգվում է հաղորդակցությունը։',
      },
      {
        id: 2,
        questionEs: 'Busca un ejemplo de función referencial.',
        questionArm: 'Գտի՛ր տեղեկատվական գործառույթի օրինակ։',
        answerEs: '“Mañana tenemos el examen de Lengua a las nueve.” (Comunica información concreta).',
        answerArm: '«Mañana tenemos el examen de Lengua a las nueve.» — Հաղորդվում է կոնկրետ տեղեկություն։',
      },
      {
        id: 3,
        questionEs: 'Busca un ejemplo de función expresiva o emotiva.',
        questionArm: 'Գտի՛ր զգացմունքային գործառույթի օրինակ։',
        answerEs: '“¡Estoy muy nervioso por el examen!” (Expresa emoción del alumno).',
        answerArm: '«¡Estoy muy nervioso por el examen!» — Արտահայտվում է զգացմունք։',
      },
      {
        id: 4,
        questionEs: 'Busca un ejemplo de función apelativa.',
        questionArm: 'Գտի՛ր դիմողական գործառույթի օրինակ։',
        answerEs: '“Repasad las funciones del lenguaje y leed bien cada pregunta.” (Pide que los alumnos actúen).',
        answerArm: '«Repasad las funciones del lenguaje y leed bien cada pregunta.» — Ուսուցիչը ցանկանում է, որ աշակերտները գործողություն կատարեն։',
      },
      {
        id: 5,
        questionEs: 'Busca un ejemplo de función metalingüística.',
        questionArm: 'Գտի՛ր մետալեզվական գործառույթի օրինակ։',
        answerEs: '““Rápidamente” es un adverbio.” (Habla sobre una categoría gramatical de la lengua).',
        answerArm: '«“Rápidamente” es un adverbio.» — Խոսվում է հենց լեզվի և բառի քերականական տեսակի մասին։',
      },
      {
        id: 6,
        questionEs: 'Busca un ejemplo de función poética.',
        questionArm: 'Գտի՛ր բանաստեղծական գործառույթի օրինակ։',
        answerEs: '“Las palabras pueden abrir puertas que las llaves no pueden abrir.” (Mensaje creativo y estético).',
        answerArm: '«Las palabras pueden abrir puertas que las llaves no pueden abrir.» — Օգտագործվում է պատկերավոր և ստեղծագործ լեզու։',
      },
      {
        id: 7,
        questionEs: 'Explica por qué cada ejemplo pertenece a esa función.',
        questionArm: 'Բացատրի՛ր, թե ինչու յուրաքանչյուր օրինակը պատկանում է այդ գործառույթին։',
        answerEs: 'Cada frase se clasifica según el elemento de la comunicación que prioriza: canal (fática), realidad (referencial), emisor (expresiva), receptor (apelativa), código (metalingüística) o mensaje estético (poética).',
        answerArm: 'Յուրաքանչյուր նախադասություն դասակարգվում է ըստ հաղորդակցության այն տարրի, որը նա կարևորում է՝ կապուղի (ֆատիկ), փաստ (տեղեկատվական), խոսող (զգացմունքային), լսող (դիմողական), կոդ (մետալեզվական), գեղագիտական ձև (բանաստեղծական)։',
      },
    ],
  },

  // Texto 6 (Texto 2 bis) — En el museo
  {
    id: 'texto-2-bis-museo',
    number: 6,
    series: 'segunda',
    titleEs: 'Texto 2 — En el museo',
    titleArm: 'Տեքստ 2 — Թանգարանում',
    subtitleEs: 'Encuentra en el texto y preguntas tipo examen',
    subtitleArm: 'Գտի՛ր տեքստում և քննության տիպի հարցեր',
    badge: 'Análisis Guiado',
    dialogue: [
      {
        speaker: 'Narrador',
        es: 'Lucía y Pablo visitan un museo de historia.',
        arm: 'Լուսիան և Պաբլոն այցելում են պատմության թանգարան։',
      },
      {
        speaker: 'Lucía',
        es: '—¿Pablo? ¿Me escuchas?',
        arm: '— Պաբլո՞։ Ինձ լսո՞ւմ ես։',
        functionId: 'fatica',
        boldPhraseEs: '¿Pablo? ¿Me escuchas?',
        boldPhraseArm: 'Պաբլո՞։ Ինձ լսո՞ւմ ես։',
      },
      {
        speaker: 'Pablo',
        es: '—Sí, estoy aquí.',
        arm: '— Այո, այստեղ եմ։',
      },
      {
        speaker: 'Lucía',
        es: '—El museo cierra a las siete de la tarde.',
        arm: '— Թանգարանը փակվում է երեկոյան ժամը յոթին։',
        functionId: 'referencial',
        boldPhraseEs: 'El museo cierra a las siete de la tarde.',
        boldPhraseArm: 'Թանգարանը փակվում է երեկոյան ժամը յոթին։',
      },
      {
        speaker: 'Lucía',
        es: '—¡Qué impresionante es todo esto!',
        arm: '— Վա՜յ, ինչ տպավորիչ է այս ամենը։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Qué impresionante es todo esto!',
        boldPhraseArm: 'Վա՜յ, ինչ տպավորիչ է այս ամենը։',
      },
      {
        speaker: 'Pablo',
        es: '—Ven aquí y mira esta herramienta prehistórica.',
        arm: '— Արի՛ այստեղ և նայի՛ր այս նախապատմական գործիքին։',
        functionId: 'apelativa',
        boldPhraseEs: 'Ven aquí y mira esta herramienta prehistórica.',
        boldPhraseArm: 'Արի՛ այստեղ և նայի՛ր այս նախապատմական գործիքին։',
      },
      {
        speaker: 'Lucía',
        es: '—La palabra “prehistoria” se refiere al periodo anterior a la aparición de la escritura.',
        arm: '— «Prehistoria» բառը նշանակում է գրի առաջացումից առաջ եղած ժամանակաշրջանը։',
        functionId: 'metalinguistica',
        boldPhraseEs: 'La palabra “prehistoria” se refiere al periodo anterior a la aparición de la escritura.',
        boldPhraseArm: '«Prehistoria» բառը նշանակում է գրի առաջացումից առաջ եղած ժամանակաշրջանը։',
      },
      {
        speaker: 'Narrador',
        es: 'Antes de entrar en la siguiente sala ven un cartel grande: “El pasado despierta cuando alguien decide escucharlo.”',
        arm: 'Հաջորդ սրահ մտնելուց առաջ նրանք տեսնում են մեծ ցուցանակ․ «Անցյալն արթնանում է, երբ ինչ-որ մեկը որոշում է լսել նրան»։',
        functionId: 'poetica',
        boldPhraseEs: '“El pasado despierta cuando alguien decide escucharlo.”',
        boldPhraseArm: '«Անցյալն արթնանում է, երբ ինչ-որ մեկը որոշում է լսել նրան»։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: 'Una frase que comprueba si funciona la comunicación.',
        questionArm: 'Մի նախադասություն, որը ստուգում է՝ հաղորդակցությունն աշխատո՞ւմ է։',
        answerEs: 'Fática: “¿Pablo? ¿Me escuchas?”',
        answerArm: 'Ֆատիկ՝ «¿Pablo? ¿Me escuchas?»',
      },
      {
        id: 2,
        questionEs: 'Una frase que simplemente informa de un hecho.',
        questionArm: 'Մի նախադասություն, որը պարզապես փաստ է հաղորդում։',
        answerEs: 'Referencial: “El museo cierra a las siete de la tarde.”',
        answerArm: 'Տեղեկատվական՝ «El museo cierra a las siete de la tarde.»',
      },
      {
        id: 3,
        questionEs: 'Una frase que expresa una emoción.',
        questionArm: 'Մի նախադասություն, որը զգացմունք է արտահայտում։',
        answerEs: 'Expresiva: “¡Qué impresionante es todo esto!”',
        answerArm: 'Զգացմունքային՝ «¡Qué impresionante es todo esto!»',
      },
      {
        id: 4,
        questionEs: 'Una frase que intenta que otra persona haga algo.',
        questionArm: 'Մի նախադասություն, որը փորձում է մյուս մարդուն գործողության դրդել։',
        answerEs: 'Apelativa: “Ven aquí y mira esta herramienta prehistórica.”',
        answerArm: 'Դիմողական՝ «Ven aquí y mira esta herramienta prehistórica.»',
      },
      {
        id: 5,
        questionEs: 'Una frase que explica el significado de una palabra.',
        questionArm: 'Մի նախադասություն, որը բացատրում է բառի իմաստը։',
        answerEs: 'Metalingüística: “La palabra ‘prehistoria’ se refiere...”',
        answerArm: 'Մետալեզվական՝ «La palabra ‘prehistoria’ se refiere...»',
      },
      {
        id: 6,
        questionEs: 'Una frase en la que importa especialmente la forma creativa del mensaje.',
        questionArm: 'Մի նախադասություն, որտեղ կարևոր է խոսքի ստեղծագործ և գեղեցիկ ձևը։',
        answerEs: 'Poética: “El pasado despierta cuando alguien decide escucharlo.”',
        answerArm: 'Բանաստեղծական՝ «El pasado despierta cuando alguien decide escucharlo.»',
      },
      {
        id: 7,
        questionEs: '¿Cuál es la función predominante en “Ven aquí y mira esta herramienta”? Justifica tu respuesta.',
        questionArm: 'Ո՞րն է գերակշռող գործառույթը «Արի՛ այստեղ և նայի՛ր այս գործիքին» նախադասության մեջ։ Հիմնավորի՛ր պատասխանը։',
        answerEs: 'Es apelativa porque utiliza imperativos (“ven”, “mira”) con el fin de influir en la conducta del receptor para que se acerque.',
        answerArm: 'Դիմողական է, որովհետև օգտագործում է հրամայական եղանակ («ven», «mira»)՝ լսողի վարքի վրա ազդելու համար։',
      },
      {
        id: 8,
        questionEs: '¿Por qué “¡Qué impresionante es todo esto!” no es principalmente referencial?',
        questionArm: 'Ինչո՞ւ «Ի՜նչ տպավորիչ է այս ամենը» նախադասությունը հիմնականում տեղեկատվական չէ։',
        answerEs: 'Porque no describe un dato comprobable o neutro, sino que expresa la admiración subjetiva de Lucía.',
        answerArm: 'Որովհետև այն չի նկարագրում չեզոք կամ օբյեկտիվ փաստ, այլ արտահայտում է Լուսիայի սուբյեկտիվ հիացմունքը։',
      },
      {
        id: 9,
        questionEs: '¿Qué palabra del texto se explica mediante la función metalingüística?',
        questionArm: 'Տեքստի ո՞ր բառն է բացատրվում մետալեզվական գործառույթի միջոցով։',
        answerEs: 'La palabra “prehistoria”.',
        answerArm: '«Prehistoria» բառը։',
      },
      {
        id: 10,
        questionEs: 'Copia la oración poética y explica qué tiene de especial.',
        questionArm: 'Արտագրի՛ր բանաստեղծական նախադասությունը և բացատրի՛ր, թե ինչով է այն առանձնահատուկ։',
        answerEs: '“El pasado despierta cuando alguien decide escucharlo.” Es especial porque personifica al “pasado” (le atribuye la capacidad de despertar y ser escuchado), creando un efecto lírico y sugerente.',
        answerArm: '«El pasado despierta cuando alguien decide escucharlo.» Առանձնահատուկ է նրանով, որ «անցյալը» անձնավորվում է (նրան վերագրվում է արթնանալու և լսվելու հատկություն)՝ ստեղծելով քնարական պատկեր։',
      },
    ],
  },

  // Texto 7 (Texto 3 bis) — Sin pistas
  {
    id: 'texto-3-bis-sinpistas',
    number: 7,
    series: 'segunda',
    titleEs: 'Texto 3 — Sin pistas',
    titleArm: 'Տեքստ 3 — Առանց հուշումների',
    subtitleEs: 'Encuentra las 6 funciones por ti mismo en el vestuario',
    subtitleArm: 'Ինքնուրույն գտիր բոլոր 6 գործառույթները',
    badge: 'Desafío Total',
    dialogue: [
      {
        speaker: 'Narrador',
        es: 'Antes de un partido, el entrenador entra en el vestuario.',
        arm: 'Խաղից առաջ մարզիչը մտնում է հանդերձարան։',
      },
      {
        speaker: 'Entrenador',
        es: '—¿Todos estáis conmigo?',
        arm: '— Բոլորդ ինձ հե՞տ եք։',
        functionId: 'fatica',
        boldPhraseEs: '¿Todos estáis conmigo?',
        boldPhraseArm: 'Բոլորդ ինձ հե՞տ եք։',
      },
      {
        speaker: 'Jugadores',
        es: 'Los jugadores asienten.',
        arm: 'Ֆուտբոլիստները գլխով հաստատում են։',
      },
      {
        speaker: 'Entrenador',
        es: '—El partido comienza dentro de veinte minutos.',
        arm: '— Խաղը սկսվում է քսան րոպեից։',
        functionId: 'referencial',
        boldPhraseEs: 'El partido comienza dentro de veinte minutos.',
        boldPhraseArm: 'Խաղը սկսվում է քսան րոպեից։',
      },
      {
        speaker: 'Sergio',
        es: '—¡Tengo muchísimas ganas de jugar, pero también estoy nervioso!',
        arm: '— Ես շա՜տ եմ ուզում խաղալ, բայց նաև նյարդայնացած եմ։',
        functionId: 'expresiva',
        boldPhraseEs: '¡Tengo muchísimas ganas de jugar, pero también estoy nervioso!',
        boldPhraseArm: 'Ես շա՜տ եմ ուզում խաղալ, բայց նաև նյարդայնացած եմ։',
      },
      {
        speaker: 'Entrenador',
        es: '—Escúchame, confía en ti y juega con calma.',
        arm: '— Լսի՛ր ինձ, վստահի՛ր քեզ և հանգիստ խաղա՛։',
        functionId: 'apelativa',
        boldPhraseEs: 'Escúchame, confía en ti y juega con calma.',
        boldPhraseArm: 'Լսի՛ր ինձ, վստահի՛ր քեզ և հանգիստ խաղա՛։',
      },
      {
        speaker: 'Jugador',
        es: '—¿Qué significa exactamente defensa en esta frase?',
        arm: '— Ի՞նչ է նշանակում defensa բառը այս նախադասության մեջ։',
      },
      {
        speaker: 'Entrenador',
        es: '—“Defensa” es el conjunto de jugadores cuya función principal es proteger la propia portería.',
        arm: '— «Defensa»-ն այն խաղացողների խումբն է, որոնց հիմնական գործառույթը սեփական դարպասը պաշտպանելն է։',
        functionId: 'metalinguistica',
        boldPhraseEs: '“Defensa” es el conjunto de jugadores cuya función principal es proteger la propia portería.',
        boldPhraseArm: '«Defensa»-ն այն խաղացողների խումբն է, որոնց հիմնական գործառույթը սեփական դարպասը պաշտպանելն է։',
      },
      {
        speaker: 'Entrenador',
        es: '—“Cada pase escribe una parte de nuestra historia.”',
        arm: '— «Յուրաքանչյուր փոխանցում գրում է մեր պատմության մի մասը»։',
        functionId: 'poetica',
        boldPhraseEs: '“Cada pase escribe una parte de nuestra historia.”',
        boldPhraseArm: '«Յուրաքանչյուր փոխանցում գրում է մեր պատմության մի մասը»։',
      },
    ],
    questions: [
      {
        id: 1,
        questionEs: 'Identifica la función Fática y su justificación.',
        questionArm: 'Գտի՛ր ֆատիկ գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: “¿Todos estáis conmigo?” | ¿Por qué?: Es fática porque comprueba si los oyentes mantienen el contacto y la atención.',
        answerArm: 'Նախադասություն՝ «¿Todos estáis conmigo?» | Ինչո՞ւ՝ Ստուգվում է հաղորդակցական կապն ու ուշադրությունը։',
      },
      {
        id: 2,
        questionEs: 'Identifica la función Referencial y su justificación.',
        questionArm: 'Գտի՛ր տեղեկատվական գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: “El partido comienza dentro de veinte minutos.” | ¿Por qué?: Es referencial porque transmite una información objetiva y verificable sobre el horario.',
        answerArm: 'Նախադասություն՝ «El partido comienza dentro de veinte minutos.» | Ինչո՞ւ՝ Հաղորդվում է կոնկրետ, օբյեկտիվ տեղեկություն ժամանակի մասին։',
      },
      {
        id: 3,
        questionEs: 'Identifica la función Expresiva y su justificación.',
        questionArm: 'Գտի՛ր զգացմունքային գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: “¡Tengo muchísimas ganas de jugar, pero también estoy nervioso!” | ¿Por qué?: Es expresiva porque el jugador comunica su propio estado anímico y nerviosismo.',
        answerArm: 'Նախադասություն՝ «¡Tengo muchísimas ganas de jugar...!» | Ինչո՞ւ՝ Արտահայտվում է խաղացողի ներքին զգացմունքն ու անհանգստությունը։',
      },
      {
        id: 4,
        questionEs: 'Identifica la función Apelativa y su justificación.',
        questionArm: 'Գտի՛ր դիմողական գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: “Escúchame, confía en ti y juega con calma.” | ¿Por qué?: Es apelativa porque el entrenador da órdenes e instrucciones directas al jugador mediante imperativos.',
        answerArm: 'Նախադասություն՝ «Escúchame, confía en ti y juega con calma.» | Ինչո՞ւ՝ Մարզիչը հրամայականներով հրահանգներ է տալիս լսողին։',
      },
      {
        id: 5,
        questionEs: 'Identifica la función Metalingüística y su justificación.',
        questionArm: 'Գտի՛ր մետալեզվական գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: Explicación de “defensa” (“‘Defensa’ es el conjunto de jugadores...”). | ¿Por qué?: Es metalingüística porque se utiliza el lenguaje para definir el significado de una palabra.',
        answerArm: 'Նախադասություն՝ «Defensa» բառի սահմանումը | Ինչո՞ւ՝ Խոսվում է հենց բառի իմաստի մասին։',
      },
      {
        id: 6,
        questionEs: 'Identifica la función Poética y su justificación.',
        questionArm: 'Գտի՛ր բանաստեղծական գործառույթը և հիմնավորումը։',
        answerEs: 'Frase: “Cada pase escribe una parte de nuestra historia.” | ¿Por qué?: Es poética porque utiliza una metáfora literaria para embellecer y dar fuerza expresiva al mensaje.',
        answerArm: 'Նախադասություն՝ «Cada pase escribe una parte de nuestra historia.» | Ինչո՞ւ՝ Օգտագործվում է պատկերավոր փոխաբերություն (գեղարվեստական լեզու)։',
      },
    ],
  },
];

export const SCRAMBLE_EXERCISES: ScrambleExerciseItem[] = [
  // Ejercicio 1 — Forma la frase
  {
    id: 101,
    series: 'ejercicio_1',
    functionId: 'referencial',
    words: ['Madrid', 'capital', 'es', 'de', 'España', 'la'],
    correctSentence: 'Madrid es la capital de España.',
    promptEs: 'Ordena las palabras para formar una oración con función referencial:',
    promptArm: 'Դասավորի՛ր բառերը և կազմի՛ր տեղեկատվական նախադասություն։',
    answerEs: 'Madrid es la capital de España.',
    answerArm: 'Մադրիդը Իսպանիայի մայրաքաղաքն է։ (Տեղեկատվական / Referencial)',
  },
  {
    id: 102,
    series: 'ejercicio_1',
    functionId: 'expresiva',
    words: ['muy', 'estoy', 'hoy', 'contento'],
    correctSentence: 'Hoy estoy muy contento.',
    promptEs: 'Ordena las palabras para expresar sentimientos (expresiva):',
    promptArm: 'Կազմի՛ր նախադասություն, որը զգացմունք է արտահայտում (զգացմունքային)։',
    answerEs: 'Hoy estoy muy contento. (o: Estoy muy contento hoy.)',
    answerArm: 'Այսօր ես շատ ուրախ եմ։ (Զգացմունքային / Expresiva)',
  },
  {
    id: 103,
    series: 'ejercicio_1',
    functionId: 'apelativa',
    words: ['puerta', 'la', 'cierra', 'favor', 'por'],
    correctSentence: 'Cierra la puerta, por favor.',
    promptEs: 'Ordena las palabras para pedir o ordenar algo (apelativa):',
    promptArm: 'Կազմի՛ր խնդրանք կամ հրահանգ (դիմողական)։',
    answerEs: 'Cierra la puerta, por favor.',
    answerArm: 'Փակի՛ր դուռը, խնդրում եմ։ (Դիմողական / Apelativa)',
  },
  {
    id: 104,
    series: 'ejercicio_1',
    functionId: 'fatica',
    words: ['escuchas', 'me', '¿', '?'],
    correctSentence: '¿Me escuchas?',
    promptEs: 'Ordena las palabras para comprobar la comunicación (fática):',
    promptArm: 'Կազմի՛ր նախադասություն, որով ստուգվում է հաղորդակցությունը (ֆատիկ)։',
    answerEs: '¿Me escuchas?',
    answerArm: 'Ինձ լսո՞ւմ ես։ (Ֆատիկ / Fática)',
  },
  {
    id: 105,
    series: 'ejercicio_1',
    functionId: 'metalinguistica',
    words: ['sustantivo', '“casa”', 'un', 'es'],
    correctSentence: '“Casa” es un sustantivo.',
    promptEs: 'Ordena las palabras para hablar de la propia lengua (metalingüística):',
    promptArm: 'Կազմի՛ր նախադասություն, որը խոսում է լեզվի մասին (մետալեզվական)։',
    answerEs: '“Casa” es un sustantivo.',
    answerArm: '«Casa» բառը գոյական է։ (Մետալեզվական / Metalingüística)',
  },
  {
    id: 106,
    series: 'ejercicio_1',
    functionId: 'poetica',
    words: ['ojos', 'estrellas', 'tus', 'como', 'brillan'],
    correctSentence: 'Tus ojos brillan como estrellas.',
    promptEs: 'Ordena las palabras para crear un mensaje poético y estético:',
    promptArm: 'Կազմի՛ր գեղեցիկ, պատկերավոր նախադասություն (բանաստեղծական)։',
    answerEs: 'Tus ojos brillan como estrellas.',
    answerArm: 'Քո աչքերը փայլում են աստղերի պես։ (Բանաստեղծական / Poética)',
  },

  // Ejercicio 2 — Sin decir la función
  {
    id: 201,
    series: 'ejercicio_2',
    functionId: 'referencial',
    words: ['mañana', 'examen', 'tenemos', 'un'],
    correctSentence: 'Mañana tenemos un examen.',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: 'Mañana tenemos un examen. → Referencial',
    answerArm: 'Վաղը քննություն ունենք։ → Տեղեկատվական (Referencial)',
  },
  {
    id: 202,
    series: 'ejercicio_2',
    functionId: 'expresiva',
    words: ['qué', 'estoy', 'cansado', '¡', '!'],
    correctSentence: '¡Qué cansado estoy!',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: '¡Qué cansado estoy! → Expresiva',
    answerArm: 'Ի՜նչ հոգնած եմ։ → Զգացմունքային (Expresiva)',
  },
  {
    id: 203,
    series: 'ejercicio_2',
    functionId: 'apelativa',
    words: ['libro', 'abre', 'tu'],
    correctSentence: 'Abre tu libro.',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: 'Abre tu libro. → Apelativa',
    answerArm: 'Բացի՛ր գիրքդ։ → Դիմողական (Apelativa)',
  },
  {
    id: 204,
    series: 'ejercicio_2',
    functionId: 'fatica',
    words: ['ahí', 'sigues', '¿', '?'],
    correctSentence: '¿Sigues ahí?',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: '¿Sigues ahí? → Fática',
    answerArm: 'Դեռ կապի մե՞ջ ես (այնտե՞ղ ես)։ → Ֆատիկ (Fática)',
  },
  {
    id: 205,
    series: 'ejercicio_2',
    functionId: 'metalinguistica',
    words: ['adjetivo', '“bonito”', 'es', 'un'],
    correctSentence: '“Bonito” es un adjetivo.',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: '“Bonito” es un adjetivo. → Metalingüística',
    answerArm: '«Bonito» բառը ածական է։ → Մետալեզվական (Metalingüística)',
  },
  {
    id: 206,
    series: 'ejercicio_2',
    functionId: 'poetica',
    words: ['mar', 'duerme', 'el', 'bajo', 'la', 'luna'],
    correctSentence: 'La luna duerme sobre el mar.',
    promptEs: 'Ordena las palabras y luego determina su función:',
    promptArm: 'Կազմի՛ր նախադասությունը, հետո որոշի՛ր գործառույթը։',
    answerEs: 'La luna duerme sobre el mar. (o: El mar duerme bajo la luna.) → Poética',
    answerArm: 'Լուսինը քնում է ծովի վրա (Ծովը քնում է լուսնի տակ)։ → Բանաստեղծական (Poética)',
  },

  // Ejercicio 3 — Más difícil
  {
    id: 301,
    series: 'ejercicio_3',
    functionId: 'referencial',
    words: ['temperatura', 'hoy', 'veinte', 'es', 'grados', 'la', 'de'],
    correctSentence: 'La temperatura hoy es de veinte grados.',
    promptEs: 'Construye una oración referencial a partir de estas palabras:',
    promptArm: 'Այս բառերից կազմի՛ր տեղեկատվական նախադասություն։',
    answerEs: 'La temperatura hoy es de veinte grados. → Referencial',
    answerArm: 'Այսօր ջերմաստիճանը քսան աստիճան է։ (Տեղեկատվական)',
  },
  {
    id: 302,
    series: 'ejercicio_3',
    functionId: 'expresiva',
    words: ['alegro', 'verte', 'cuánto', 'me', '¡', '!'],
    correctSentence: '¡Cuánto me alegro de verte!',
    promptEs: 'Construye una oración expresiva:',
    promptArm: 'Կազմի՛ր զգացմունքային նախադասություն։',
    answerEs: '¡Cuánto me alegro de verte! → Expresiva',
    answerArm: 'Որքա՜ն եմ ուրախանում քեզ տեսնելով։ (Զգացմունքային)',
  },
  {
    id: 303,
    series: 'ejercicio_3',
    functionId: 'apelativa',
    words: ['silencio', 'por', 'guarda', 'favor'],
    correctSentence: 'Guarda silencio, por favor.',
    promptEs: 'Construye una oración apelativa:',
    promptArm: 'Կազմի՛ր դիմողական նախադասություն։',
    answerEs: 'Guarda silencio, por favor. → Apelativa',
    answerArm: 'Լռությո՛ւն պահպանիր, խնդրում եմ։ (Դիմողական)',
  },
  {
    id: 304,
    series: 'ejercicio_3',
    functionId: 'fatica',
    words: ['bien', 'oye', 'me', '¿', 'se', '?'],
    correctSentence: '¿Se me oye bien?',
    promptEs: 'Construye una oración fática:',
    promptArm: 'Կազմի՛ր ֆատիկ նախադասություն։',
    answerEs: '¿Se me oye bien? → Fática',
    answerArm: 'Ինձ լա՞վ են լսում (ձայնս լա՞վ է գալիս)։ (Ֆատիկ)',
  },
  {
    id: 305,
    series: 'ejercicio_3',
    functionId: 'metalinguistica',
    words: ['verbo', '“correr”', 'un', 'es'],
    correctSentence: '“Correr” es un verbo.',
    promptEs: 'Construye una oración metalingüística:',
    promptArm: 'Կազմի՛ր մետալեզվական նախադասություն։',
    answerEs: '“Correr” es un verbo. → Metalingüística',
    answerArm: '«Correr» բառը բայ է։ (Մետալեզվական)',
  },
  {
    id: 306,
    series: 'ejercicio_3',
    functionId: 'poetica',
    words: ['viento', 'secretos', 'susurra', 'el'],
    correctSentence: 'El viento susurra secretos.',
    promptEs: 'Construye una oración poética:',
    promptArm: 'Կազմի՛ր բանաստեղծական նախադասություն։',
    answerEs: 'El viento susurra secretos. → Poética',
    answerArm: 'Քամին գաղտնիքներ է շշնջում։ (Բանաստեղծական)',
  },

  // Ejercicio 4 — Crea tú la frase
  {
    id: 401,
    series: 'ejercicio_4',
    functionId: 'referencial',
    promptEs: 'Escribe una frase referencial sobre el colegio.',
    promptArm: 'Գրիր տեղեկատվական նախադասություն դպրոցի մասին։',
    answerEs: 'Las clases empiezan a las ocho.',
    answerArm: 'Դասերը սկսվում են ժամը ութին։ (Տեղեկատվական — փաստ դպրոցի մասին)',
    explanationArm: 'Տեղեկատվական է, որովհետև հաղորդում է օբյեկտիվ փաստ առանց անձնական զգացմունքների։',
  },
  {
    id: 402,
    series: 'ejercicio_4',
    functionId: 'expresiva',
    promptEs: 'Escribe una frase expresiva sobre un examen.',
    promptArm: 'Գրիր զգացմունքային նախադասություն քննության մասին։',
    answerEs: '¡Estoy muy nervioso por el examen!',
    answerArm: 'Ես շա՜տ եմ անհանգստանում քննության պատճառով։',
    explanationArm: 'Զգացմունքային է, որովհետև խոսողն արտահայտում է իր ներքին հույզերն ու անհանգստությունը։',
  },
  {
    id: 403,
    series: 'ejercicio_4',
    functionId: 'apelativa',
    promptEs: 'Escribe una frase apelativa dirigida a un compañero.',
    promptArm: 'Գրիր դիմողական նախադասություն՝ ուղղված դասընկերոջը։',
    answerEs: 'Ayúdame con este ejercicio, por favor.',
    answerArm: 'Օգնի՛ր ինձ այս վարժության հարցում, խնդրում եմ։',
    explanationArm: 'Դիմողական է, որովհետև ուղղված է լսողին՝ որևէ գործողություն կատարելու խնդրանքով կամ հրամանով։',
  },
  {
    id: 404,
    series: 'ejercicio_4',
    functionId: 'fatica',
    promptEs: 'Escribe una frase fática para comprobar si alguien te escucha.',
    promptArm: 'Գրիր ֆատիկ նախադասություն՝ ստուգելու համար, թե քեզ լսո՞ւմ են։',
    answerEs: '¿Me oyes bien?',
    answerArm: 'Ինձ լա՞վ ես լսում։',
    explanationArm: 'Ֆատիկ է, որովհետև նպատակն է ստուգել հաղորդակցական կապի աշխատանքը։',
  },
  {
    id: 405,
    series: 'ejercicio_4',
    functionId: 'metalinguistica',
    promptEs: 'Escribe una frase metalingüística sobre una palabra.',
    promptArm: 'Գրիր մետալեզվական նախադասություն որևէ բառի մասին։',
    answerEs: '“Rápidamente” es un adverbio.',
    answerArm: '«Rápidamente» բառը մակբայ է։',
    explanationArm: 'Մետալեզվական է, որովհետև լեզուն օգտագործվում է հենց լեզվական միավոր բացատրելու համար։',
  },
  {
    id: 406,
    series: 'ejercicio_4',
    functionId: 'poetica',
    promptEs: 'Escribe una frase poética sobre la noche.',
    promptArm: 'Գրիր բանաստեղծական նախադասություն գիշերվա մասին։',
    answerEs: 'La noche cubre la ciudad con un manto oscuro.',
    answerArm: 'Գիշերը մութ թիկնոցով պատում է քաղաքը։',
    explanationArm: 'Բանաստեղծական է, որովհետև օգտագործվում է պատկերավոր, գեղարվեստական լեզու և փոխաբերություն։',
  },
];
